version: 1.0.0-{branch}-{build}

image: Visual Studio 2017

configuration: Release

build:
  parallel: false
  project: Flurl.sln 

before_build:
  - cmd: dotnet restore -v m

test_script:
  - cmd: call cmd /C "cd .\build & test.cmd"

artifacts:
  - path: '**\*.nupkg'