version: 1.0.0-{branch}-{build}

branches:
  only:
    - master
    - dev

pull_requests:
  do_not_increment_build_number: true

build_script:
  - cmd: call cmd /C "call dotnet --info & cd .\build & pack.flurl.cmd & pack.flurl.http.cmd"  

test_script:
  - cmd: call cmd /C "cd .\build & test.cmd"

artifacts:
  - path: '**\*.nupkg'